formatter: "markdown"

header-from: ./.config/header.md
footer-from: ./.config/footer.md

output:
  file: ./README.md
  mode: replace
  template: |-
    {{ .Content }}

sections:
  hide:
    - modules

content: |-
  # AWS Inspector Organization configuration Terraform module
  A Terraform module which configures your AWS Inspector. https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html
  {{ .Header }}

  ## Example
  ```hcl
  {{ include "./example/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
